default:
  aws:
    region: eu-west-1
    accounts:
      deploy: "092113928458"
      data: "534282717446"
      etl: "319406913669"

    tags:
      Application: "Containers"
      Environment: "@format {this.current_env}"

  # Tag for the docker image
  image_tag: "local"

tst:
  # To be overwritten by pipeline in DYNACONF_BUILD_NUMBER
  image_tag: "@format {this.build_number}-ci"

publish:
  image_tag: "@format {this.build_number}"